version: "3"
networks:
  homesforstudents:
services:
  web:
    container_name: homesforstudents_web
    networks:
      - homesforstudents
    build: .
    tty: true
    stdin_open: true
    volumes:
      - ./src:/var/www/html
      - ./config/000-default.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - 8087:80
      - 3357:3306
